//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Cntrl.Lab_03_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string class1 { get; set; }
        public string type { get; set; }
        public string country { get; set; }
        public Nullable<byte> numGuns { get; set; }
        public Nullable<float> bore { get; set; }
        public Nullable<int> displacement { get; set; }
    }
}
