//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Cntrl.Lab_03_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public string ship { get; set; }
        public string battle { get; set; }
        public string result { get; set; }
    }
}
