//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Cntrl.Lab_03_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public string name { get; set; }
        public string @class { get; set; }
        public Nullable<short> launched { get; set; }
    }
}
